# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'divide-ios' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for divide-ios
  pod 'GRMustache', '~> 7.3.2'
  pod 'JSONModel'
end
